"""LibreOffice conversion Lambda (container image).

Input:
  {
    "bucket": "...",
    "key": "raw/xxx.xlsx",
    "report_id": "..."
  }

Output:
  {
    "bucket": "...",
    "key": "converted/<report_id>/<file>.pdf",
    "report_id": "...",
    "convertedPrefix": "converted/<report_id>/",
    "convertedCount": 1
  }
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
import boto3  # type: ignore[import-not-found]

s3 = boto3.client("s3")

# Lambda コンテナは $HOME 以外が読み取り専用のため、LibreOffice のユーザープロファイルは /tmp に置く
_USER_INSTALL_DIR = Path("/tmp/libreoffice-user-install")


def handler(event, context):
    bucket = event["bucket"]
    key = event["key"]
    report_id = event.get("report_id") or _derive_report_id(key)

    workdir = Path("/tmp/libreoffice")
    workdir.mkdir(parents=True, exist_ok=True)

    input_path = workdir / Path(key).name
    s3.download_file(bucket, key, str(input_path))

    # LibreOffice / ファイルシステムの相性問題を避けるため ASCII 名で変換する。
    # 拡張子を保持することで LibreOffice がファイル種別を正しく認識する。
    src_ext = Path(key).suffix.lower()
    convert_input = workdir / f"input{src_ext}"
    shutil.copy(input_path, convert_input)

    # ファイル種別に合わせた LibreOffice フィルタを選択する
    if src_ext in (".xlsx", ".xls", ".ods", ".csv"):
        pdf_filter = "pdf:calc_pdf_Export"
    elif src_ext in (".docx", ".doc", ".odt", ".rtf"):
        pdf_filter = "pdf:writer_pdf_Export"
    elif src_ext in (".pptx", ".ppt", ".odp"):
        pdf_filter = "pdf:impress_pdf_Export"
    else:
        pdf_filter = "pdf"

    pdf_dir = workdir / "pdf"
    png_dir = workdir / "png"
    pdf_dir.mkdir(exist_ok=True)
    png_dir.mkdir(exist_ok=True)

    _convert_to_pdf(convert_input, pdf_dir, pdf_filter)
    _convert_to_png(convert_input, png_dir)

    pdf_files = sorted(pdf_dir.glob("*.pdf")) + sorted(pdf_dir.glob("*.PDF"))
    if not pdf_files:
        listing = [p.name for p in workdir.rglob("*") if p.is_file()]
        raise RuntimeError(
            "No PDF files were generated by LibreOffice conversion; "
            f"workdir files={listing}"
        )

    output_prefix = f"converted/{report_id}/"
    uploaded_keys: list[str] = []
    for pdf in pdf_files:
        output_key = f"{output_prefix}{pdf.name}"
        s3.upload_file(str(pdf), bucket, output_key)
        uploaded_keys.append(output_key)

    image_prefix = f"images/{report_id}/"
    for png in sorted(png_dir.glob("*.png")) + sorted(png_dir.glob("*.PNG")):
        image_key = f"{image_prefix}{png.name}"
        s3.upload_file(str(png), bucket, image_key)

    return {
        "bucket": bucket,
        "key": uploaded_keys[0],
        "report_id": report_id,
        "convertedPrefix": output_prefix,
        "convertedCount": len(uploaded_keys),
        "imagePrefix": image_prefix,
    }


def _convert_to_pdf(input_path: Path, output_dir: Path, pdf_filter: str = "pdf:calc_pdf_Export") -> None:
    _run_libreoffice(input_path, output_dir, pdf_filter)


def _convert_to_png(input_path: Path, output_dir: Path) -> None:
    _run_libreoffice(input_path, output_dir, "png")


def _run_libreoffice(input_path: Path, output_dir: Path, target_format: str) -> None:
    _USER_INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    user_install_uri = _USER_INSTALL_DIR.resolve().as_uri()
    cmd = [
        "libreoffice",
        "--headless",
        "--invisible",
        "--norestore",
        f"-env:UserInstallation={user_install_uri}",
        "--convert-to",
        target_format,
        "--outdir",
        str(output_dir),
        str(input_path),
    ]
    env = {
        **os.environ,
        "HOME": "/tmp",
        "TMPDIR": "/tmp",
        # ディスプレイ不要の VCL プラグイン（Lambda 向け）
        "SAL_USE_VCLPLUGIN": "svp",
    }
    result = subprocess.run(
        cmd, capture_output=True, text=True, check=False, env=env
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"LibreOffice {target_format} conversion failed: {result.stdout}\n{result.stderr}"
        )
    outputs = [p for p in output_dir.iterdir() if p.is_file()]
    if not outputs:
        raise RuntimeError(
            f"LibreOffice {target_format} produced no output in {output_dir}: "
            f"{result.stdout}\n{result.stderr}"
        )


def _derive_report_id(key: str) -> str:
    name = Path(key).stem
    return name.replace(" ", "_")
